name: Auto-update latenzy subtree

on:
  # Run on a schedule (every hour here, change as needed)
  schedule:
    - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch: {}

permissions:
  contents: write  # needed to push commits

jobs:
  update-latenzy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout zetatest
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add latenzy as remote
        run: |
          git remote add latenzy https://github.com/Herseninstituut/latenzy.git || true
          git fetch latenzy

      - name: Pull latest latenzy into subtree
        run: |
          git subtree pull --prefix=latenzy latenzy main --squash -m "Auto-update latenzy subtree"

      - name: Push changes if any
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
